**The purpose of this notebook is to add data on each show examined on whether the show won a Tony award in each of four major categories.**

In [1]:
#Loading Necessary Packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [2]:
#Loading full data set, Tony data set, and set with number of weeks each show survived
tony = pd.read_csv('/Users/morganhogenmiller/Desktop/GitHub/DA_401/Data sets/Tonywinsm.csv') # read in Tony data
Broadway_Original = pd.read_csv('/Users/morganhogenmiller/Desktop/GitHub/DA_401/Data sets/broadway(corgi) copy.csv') #Read in CORGI data set
weeks=pd.read_csv('/Users/morganhogenmiller/Desktop/GitHub/DA_401/Data sets/selfedited.csv')

In [3]:
#Filter to musicals after 2007 only
Google_Parameters= Broadway_Original[['Name','Year','Month','Day','Type']] #Reduce data set to variables to input into GT
Google_Parameters=Google_Parameters.loc[Google_Parameters['Year']>2007] 
Google_Parameters=Google_Parameters.loc[Google_Parameters['Type']=='Musical']

In [4]:
#Redefining show list based upon the shows as they are named in the Tony data set
show_list = ['13',
 '9 To 5',
 'A Catered Affair',
 "A Chorus Line '06",
 'A Christmas Story',
 "A Gentleman's Guide To Love And Murder",
 'A Little Night Music',
 'A Night With Janis Joplin',
 'A Tale Of Two Cities',
 'After Midnight',
 'Aladdin',
 'All About Me',
 'Allegiance',
 'Amazing Grace',
 'American Idiot',
 'American Psycho',
 'An American In Paris',
 "Annie '12",
 "Anything Goes",
 'Avenue Q',
 "Baby It'S You!",
 'Beautiful: The Carole King Musical',
 'Big Fish',
 'Billy Elliot: The Musical',
 'Bloody Bloody Andrew Jackson',
 'Bonnie And Clyde',
 'Bright Star',
 'Bring It On The Musical',
 'Bullets Over Broadway',
 'Burn The Floor',
 'Bye Bye Birdie',
 'Cabaret',
 'Catch Me If You Can',
 'Cats 2016',
 'Chaplin',
 'Chicago',
 'Cinderella',
 'Come Fly Away',
 'Cry Baby',
 'Curtains',
 'Dames At Sea',
 'Disaster!',
 'Doctor Zhivago',
 "Dr. Seuss' How The Grinch Stole Christmas! 07",
 'Elf',
 "Elf '12",
 'Everyday Rapture',
 'Evita',
 'Fela!',
 'Fiddler On The Roof 2015',
 'Finding Neverland',
 "Finian's Rainbow",
 'First Date',
 "Follies '11",
 'Fun Home',
 'Ghost',
 'Gigi',
 'Glory Days',
 'Godspell',
 'Grease 07',
 "Guys And Dolls",
 "Gypsy '08",
 'Hair',
 "Hair",
 'Hairspray',
 'Hamilton (musical)',
 'Hands On A Hardbody',
 'Hedwig And The Angry Inch',
 'Holler If Ya Hear Me',
 'Honeymoon In Vegas',
 "How To Succeed In Business Without Really Trying '11",
 'If/Then',
 'In The Heights',
 "Irving Berlin'S White Christmas",
 "Irving Berlin'S White Christmas '09",
 'It Shoulda Been You',
 "Jekyll & Hyde '13",
 'Jersey Boys',
 "Jesus Christ Superstar '12",
 'Kinky Boots',
 "La Cage aux Folles",
 'Leap Of Faith',
 'Legally Blonde',
 'Les Miserables (musical)',
 'Lysistrata Jones',
 'Mamma Mia!',
 'Mary Poppins',
 'Matilda',
 'Memphis',
 'Million Dollar Quartet',
 "Monty Python's Spamalot",
 'Motown The Musical',
 'Motown The Musical 2016',
 'Newsies',
 'Next To Normal',
 'Nice Work If You Can Get It',
 'On A Clear Day You Can See Forever',
 'On The Town',
 'On The Twentieth Century',
 'On Your Feet!',
 'On the Town (musical)',
 'Once',
 'Pal Joey',
 'Paramour',
 'Passing Strange',
 'Pippin',
 "Porgy And Bess '11",
 'Priscilla Queen Of The Desert',
 'Promises, Promises',
 "Ragtime '09",
 'Rain: A Tribute To The Beatles On Broadway',
 'Rent',
 'Rock Of Ages',
 'Rocky',
 'Scandalous',
 'School Of Rock',
 'She Loves Me 2016',
 'Shrek The Musical',
 'Shuffle Along',
 'Side Show 2014',
 'Sister Act',
 'Something Rotten!',
 'Sondheim On Sondheim',
 'Soul Doctor',
 'South Pacific',
 'Spider-Man Turn Off The Dark',
 'Spring Awakening',
 "Sunday In The Park With George '08",
 'The 25Th Annual Putnam County Spelling Bee',
 'The Addams Family',
 'The Book Of Mormon',
 'The Bridges Of Madison County',
 'The Color Purple',
 'The Color Purple 2015',
 'The King and I 2015',
 'The Last Ship',
 'The Lion King',
 'The Little Mermaid',
 "The Mystery Of Edwin Drood '12",
 'The People in the Picture',
 'The Phantom Of The Opera',
 'The Scottsboro Boys',
 'The Story Of My Life',
 'The Visit 2015',
 'Title Of Show',
 'Tuck Everlasting',
 'Violet',
 'Waitress',
 'West Side Story',
 'Wicked',
 'Women On The Verge Of A Nervous Breakdown',
 'Wonderland',
 'Xanadu',
 'Young Frankenstein']

In [5]:
#Creating data set with Boolean variables for if a show won a Tony in each major category

def tonys(shows):
    """
    This function takes a list of shows and creates a boolean variable for each award category in the big four, 
    ultimately to get information for if the show won a Tony in each of the categories. The function takes "shows"
    as a parameter, which is a list of the shows to be examined in relation to the Tony data set from years 2008 to 2016.
    """

    musical=[]
    revival=[]
    director=[]
    actor=[]
    actress=[]

    for i in show_list:
        if i in list(tony.iloc[:,1]): #add 1 for best musical winners
            musical.append(1)
        else: 
            musical.append(0)

        if i in list(tony.iloc[:,2]): #add 1 for best revival
            revival.append(1)
        else: 
            revival.append(0)

        if i in list(tony.iloc[:,3]): #add 1 for best director
            director.append(1)
        else: 
            director.append(0)
        if i in list(tony.iloc[:,5]): #add 1 for best actor
            actor.append(1)
        else: 
            actor.append(0)
        if i in list(tony.iloc[:,4]): #add 1 for best actress
            actress.append(1)
        else: 
            actress.append(0)


    Tony=pd.DataFrame({'Name': show_list, 'Best Musical':musical, 'Best Revival':revival, 'Best Director':director, 'Best Actor':actor,'Best Actress':actress})
    return Tony

In [6]:
Tony=tonys(show_list)

In [7]:
#Adding a column to the data for the total number of Tonys each show wins
Tony['total']=Tony['Best Musical']+Tony['Best Revival']+Tony['Best Director'] + Tony['Best Actor'] + Tony['Best Actress']
weeks= weeks.loc[:,['Weeks','Name']]

#Merging Tony data with number of weeks a show was on Broadway 
Tony=Tony.join(weeks.set_index('Name'),on='Name')
Tony

,Best Actor,Best Actress,Best Director,Best Musical,Best Revival,Name,total,Weeks
0,0,0,0,0,0,13,0,14.0
1,0,0,0,0,0,9 To 5,0,22.0
2,0,0,0,0,0,A Catered Affair,0,NaN
3,0,0,0,0,0,A Chorus Line '06,0,33.0
4,0,0,0,0,0,A Christmas Story,0,7.0
5,0,0,0,0,0,A Gentleman's Guide To Love And Murder,0,NaN
6,0,1,0,0,0,A Little Night Music,1,56.0
7,0,0,0,0,0,A Night With Janis Joplin,0,21.0
8,0,0,0,0,0,A Tale Of Two Cities,0,12.0
9,0,0,0,0,0,After Midnight,0,37.0
10,0,0,0,0,0,Aladdin,0,129.0
11,0,0,0,0,0,All About Me,0,NaN
12,0,0,0,0,0,Allegiance,0,19.0
13,0,0,0,0,0,Amazing Grace,0,18.0
14,0,0,0,0,0,American Idiot,0,57.0
15,0,0,0,0,0,American Psycho,0,11.0
16,0,0,0,0,0,An American In Paris,0,75.0
17,0,0,0,0,0,Annie '12,0,66.0
18,0,1,0,0,1,Anything Goes,2,NaN
19,0,0,0,0,0,Avenue Q,0,89.0
20,0,0,0,0,0,Baby It'S You!,0,24.0
21,0,1,0,0,0,Beautiful: The Carole King Musical,1,143.0
22,0,0,0,0,0,Big Fish,0,17.0
23,1,0,1,1,0,Billy Elliot: The Musical,3,171.0
24,0,0,0,0,0,Bloody Bloody Andrew Jackson,0,15.0
25,0,0,0,0,0,Bonnie And Clyde,0,9.0
26,0,0,0,0,0,Bright Star,0,18.0
27,0,0,0,0,0,Bring It On The Musical,0,25.0
28,0,0,0,0,0,Bullets Over Broadway,0,24.0
29,0,0,0,0,0,Burn The Floor,0,25.0
...,...,...,...,...,...,...,...,...
124,1,0,1,0,1,South Pacific,3,130.0
125,0,0,0,0,0,Spider-Man Turn Off The Dark,0,160.0
126,0,0,1,1,0,Spring Awakening,2,75.0
127,0,0,0,0,0,Sunday In The Park With George '08,0,23.0
128,0,0,0,0,0,The 25Th Annual Putnam County Spelling Bee,0,3.0
129,0,0,0,0,0,The Addams Family,0,95.0
130,0,0,1,1,0,The Book Of Mormon,2,286.0
131,0,0,0,0,0,The Bridges Of Madison County,0,18.0
132,0,1,0,0,0,The Color Purple,1,NaN
133,0,0,0,0,0,The Color Purple 2015,0,40.0
134,0,0,0,0,0,The King and I 2015,0,NaN
135,0,0,0,0,0,The Last Ship,0,17.0
136,0,0,0,0,0,The Lion King,0,450.0
137,0,0,0,0,0,The Little Mermaid,0,87.0
138,0,0,0,0,0,The Mystery Of Edwin Drood '12,0,21.0
139,0,0,0,0,0,The People in the Picture,0,12.0
140,0,0,0,0,0,The Phantom Of The Opera,0,450.0
141,0,0,0,0,0,The Scottsboro Boys,0,10.0
142,0,0,0,0,0,The Story Of My Life,0,3.0
143,0,0,0,0,0,The Visit 2015,0,12.0
144,0,0,0,0,0,Title Of Show,0,NaN
145,0,0,0,0,0,Tuck Everlasting,0,9.0
146,0,0,0,0,0,Violet,0,NaN
147,0,0,0,0,0,Waitress,0,21.0
148,0,0,0,0,0,West Side Story,0,97.0
149,0,0,0,0,0,Wicked,0,450.0
150,0,0,0,0,0,Women On The Verge Of A Nervous Breakdown,0,13.0
151,0,0,0,0,0,Wonderland,0,8.0
152,0,0,0,0,0,Xanadu,0,39.0
153,0,0,0,0,0,Young Frankenstein,0,NaN

The chuck below is commented out because it was only needed once to export the data as a csv.

In [8]:
# Export data as a csv
#pd.DataFrame.to_csv(Tony,'Tonys.csv')